CREATE TABLE POST
( 
	POST_IDX INT NOT NULL AUTO_INCREMENT,
	POST_CATEGORY INT NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENTS VARCHAR(4000) NOT NULL,
	DEL_STATUS VARCHAR(1) NOT NULL DEFAULT 'N',
	REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	WRITER INT NOT NULL DEFAULT 0,
	PRIMARY KEY(POST_IDX)
);

CREATE TABLE COMMENT
(
	COMMENT_IDX INT NOT NULL AUTO_INCREMENT,
	POST_IDX INT NOT NULL,
	CONTENTS VARCHAR(4000) NOT NULL,
	DEL_STATUS VARCHAR(1) NOT NULL DEFAULT 'N',
	REG_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	WRITER INT NOT NULL,
	PRIMARY KEY(COMMENT_IDX)
);

CREATE TABLE CATEGORY_MASTER
(
	CATE_CODE INT NOT NULL,
	CATE_TITLE varchar(60) NOT NULL,
	PRIMARY KEY(CATE_CODE)
);

CREATE TABLE USER
(
	USER_CODE INT NOT NULL AUTO_INCREMENT,
	USER_ID varchar(20) NOT NULL,
	PASSWORD varchar(16) NOT NULL,
	NICK_NAME varchar(60) NOT NULL,
	AUTHORITY char(1) NOT NULL DEFAULT '1',
	PRIMARY KEY(USER_CODE)
);